language: csharp
mono:
  - 3.12.1
sudo: false  # use the new container-based infrastructure
install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
script:
  - . ./build.sh
